### PR TITLE
Export unordered as a SendmsgFlag as well

### PR DESCRIPTION
**Pull request by shlevy**
On top of #8 because it defines the SendmsgFlag type.

### CODE REVIEW

**Comment by lpeterse** [comment]
Hi, I see you're making continuous progress. Tell when I shall finally merge or package your changes.
If you like to, you may also have maintainership on the Hackage package. You're the only one I know of that is currently using/working on this package and I it's a bit bitrotten as I'm currently not using it myself.

**Comment by shlevy** [comment]
Hi, I think (80% sure) this is the last change I will need in the short term, so a merge/new release would be great!

I'm also happy to take over maintainership if you'd like, I will need to keep this working for the foreseeable future and will probably want to use it in other projects now that I know how great sctp is :grin:

**Comment by lpeterse** [comment]
Mhh, adding you through the webinterface does not work right now. Could you bump the version, add yourself and your repository/issue tracker in the .cabal file and send another pull request? I'll upload a release which should automatically make you a maintainer then.

**Comment by shlevy** [comment]
@lpeterse Sure! Should I include #6 in that PR?

**Comment by lpeterse** [comment]
Include anything you like. I see there is a conflict with my master now. Would be great if you could resolve that.

**Comment by lpeterse** [comment]
I've lost orientation ;-)

**Pull request merged**
